# yaml-language-server:
# $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
words:
  - rbxl
  - rbxm
  - rbxlx
  - rbxmx
  - rbxtsc
  - rojo
  - scriptable
