# yaml-language-server:
# $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en

words:
  - arktype
  - catchable
  - codegen
  - darklua
  - defu
  - forgerc
  - napi
  - pathext
  - pids
  - rbxl
  - rbxlx
  - rbxm
  - rbxmx
  - rbxts
  - rbxtsc
  - rojo
  - scriptable
  - subreaper
  - syncback
  - taskkill
  - tsgolint
  - unstub
