import isentinel from "@isentinel/eslint-config";

export default isentinel({
	flawless: true,
	// Generated by the skills CLI; rewritten on every `npx skills` run.
	ignores: ["skills-lock.json"],
	roblox: false,
	type: "package",
});
