import path from "node:path";
import { describe, expect, it, vi } from "vitest";

import {
	createCommandContext,
	createMemoryFileSystem,
	createRecordingReporter,
	createTestSeams,
	PROJECT,
} from "../../test/helpers/seams.ts";
import type { MemoryFileSystem, RecordingReporter } from "../../test/helpers/seams.ts";
import type { ConfigLayer } from "../config/schema.ts";
import type { ProcessOutcome, ProcessRunner, ProcessSpec } from "../process/process-runner.ts";
import type { ConfigLoader } from "../seams/config-loader.ts";
import type { CommandContext, CommandInput } from "./context.ts";
import { runTypegenCommandAsync } from "./typegen.ts";

const TOOLS = path.join(PROJECT, "tools");
const ROJO = path.join(TOOLS, "rojo");
const SOURCEMAP = path.join(".forge", "sourcemap.json");
const HEADER = "// This file is autogenerated by rbx-forge. Do not modify.";

/** A place with a model and a script, as `rojo sourcemap` writes it. */
const PLACE = [
	'{"name":"game","className":"DataModel","children":[',
	'{"name":"ReplicatedStorage","className":"ReplicatedStorage","children":[',
	'{"name":"Assets","className":"Folder","children":[{"name":"Sword","className":"Tool"}]}]},',
	'{"name":"Workspace","className":"Workspace","children":[',
	'{"name":"Map","className":"Model"},{"name":"Map","className":"Model"}]}]}',
].join("");

interface TypegenSetup {
	/** The config file's content besides `projectType: "rbxts"`. */
	file?: object;
	/** Extra files besides the Rojo executable. */
	files?: Record<string, string>;
	/** What each spawn returns, by label: `rojo` or a hook's command line. */
	outcomes?: Record<string, ProcessOutcome>;
	/** What Rojo writes to its output; nothing when `null`. */
	sourcemap?: null | string;
}

interface TypegenRun {
	context: CommandContext;
	memory: MemoryFileSystem;
	/** What ran, in order: `rojo` or a hook's command line. */
	order: () => Array<string>;
	reporter: RecordingReporter;
	specs: Array<ProcessSpec>;
}

function exited(exitCode: number, outputTail: Array<string> = []): ProcessOutcome {
	return { durationMs: 700, exitCode, outputTail, signal: null, type: "exited" };
}

function labelOf(spec: ProcessSpec): string {
	return spec.file === "/bin/sh" ? spec.args[1]! : "rojo";
}

function makeTypegen({
	file = {},
	files = { "tools/rojo": "" },
	outcomes = {},
	sourcemap = PLACE,
}: TypegenSetup = {}): TypegenRun {
	const memory = createMemoryFileSystem(files);
	const specs: Array<ProcessSpec> = [];
	const processRunner = vi.fn<ProcessRunner>(async (spec) => {
		specs.push(spec);
		const label = labelOf(spec);
		const outcome = outcomes[label];
		// Rojo writes the sourcemap (argument 3) only when it succeeds.
		if (sourcemap !== null && label === "rojo" && outcome === undefined) {
			memory.fileSystem.writeFileSync(path.resolve(spec.cwd, spec.args[3]!), sourcemap);
		}

		return outcome ?? exited(0);
	});
	const configLoader = vi.fn<ConfigLoader>().mockResolvedValue({
		path: path.join(PROJECT, "rbx-forge.config.ts"),
		value: { projectType: "rbxts", ...file },
	});
	const reporter = createRecordingReporter();

	return {
		context: createCommandContext({
			env: { PATH: TOOLS },
			reporter,
			seams: createTestSeams({ configLoader, fileSystem: memory.fileSystem, processRunner }),
		}),
		memory,
		order: () => specs.map(labelOf),
		reporter,
		specs,
	};
}

function input(flags: CommandInput["flags"] = {}, config: ConfigLayer = {}): CommandInput {
	return { config, flags };
}

describe(runTypegenCommandAsync, () => {
	it("should write the service types of Rojo's sourcemap to the configured output", async () => {
		expect.assertions(3);

		const { context, memory, specs } = makeTypegen();
		const output = path.join(PROJECT, "src", "services.d.ts");

		await expect(runTypegenCommandAsync(context, input())).resolves.toStrictEqual({
			data: {
				duplicates: ["Workspace/Map"],
				durationMs: 700,
				hooks: [],
				output,
				services: ["ReplicatedStorage", "Workspace"],
			},
			summary: `Wrote ${output}.`,
		});
		expect(specs).toStrictEqual([
			{
				args: [
					"sourcemap",
					"default.project.json",
					"--output",
					SOURCEMAP,
					"--include-non-scripts",
				],
				cwd: PROJECT,
				env: { PATH: TOOLS },
				file: ROJO,
			},
		]);
		expect(memory.files()["src/services.d.ts"]).toBe(`${HEADER}

interface ReplicatedStorage {
	Assets: Folder & {
		Sword: Tool;
	};
}

interface Workspace {
	Map: Model;
}
`);
	});

	it("should read the configured project and write to --output", async () => {
		expect.assertions(2);

		const { context, memory, specs } = makeTypegen({
			file: { rojoProjectPath: "place.project.json" },
		});
		await runTypegenCommandAsync(
			context,
			input({ output: "types/game.d.ts" }, { typegen: { outputPath: "types/game.d.ts" } }),
		);

		expect(specs[0]!.args[1]).toBe("place.project.json");
		expect(memory.files()).toContainKey("types/game.d.ts");
	});

	it("should apply the configured filters", async () => {
		expect.assertions(1);

		const { context, memory } = makeTypegen({
			file: { typegen: { exclude: ["Workspace"], include: ["**/Assets"], maxDepth: 2 } },
		});
		await runTypegenCommandAsync(context, input());

		expect(memory.files()["src/services.d.ts"]).toBe(
			`${HEADER}\n\ninterface ReplicatedStorage {\n\tAssets: Folder;\n}\n`,
		);
	});

	it("should warn about each sibling left out for its name", async () => {
		expect.assertions(1);

		const { context, reporter } = makeTypegen();
		await runTypegenCommandAsync(context, input());

		expect(reporter.events).toContainEqual({
			message:
				"Skipped Workspace/Map: an earlier sibling has the same name, and a type can hold only one.",
			type: "warning",
		});
	});

	it("should remove the sourcemap after reading it", async () => {
		expect.assertions(1);

		const { context, memory } = makeTypegen();
		await runTypegenCommandAsync(context, input());

		expect(memory.files()).not.toContainKey(".forge/sourcemap.json");
	});

	it("should fail with sourcemap_invalid when Rojo writes no sourcemap", async () => {
		expect.assertions(2);

		const { context, memory } = makeTypegen({ sourcemap: null });

		await expect(runTypegenCommandAsync(context, input())).rejects.toMatchObject({
			code: "sourcemap_invalid",
			hint: "Check that rojoAlias runs Rojo, not another tool.",
			message: `Rojo exited without writing the sourcemap to ${SOURCEMAP}.`,
		});
		expect(memory.files()).not.toContainKey("src/services.d.ts");
	});

	it("should fail with sourcemap_invalid and remove a sourcemap it cannot read", async () => {
		expect.assertions(2);

		const { context, memory } = makeTypegen({ sourcemap: '{"name":"game"}' });

		await expect(runTypegenCommandAsync(context, input())).rejects.toMatchObject({
			code: "sourcemap_invalid",
		});
		expect(memory.files()).not.toContainKey(".forge/sourcemap.json");
	});

	it("should fail with process_failed when Rojo fails", async () => {
		expect.assertions(2);

		const { context, memory } = makeTypegen({
			outcomes: { rojo: exited(1, ["[ERROR] no such project"]) },
		});

		await expect(runTypegenCommandAsync(context, input())).rejects.toMatchObject({
			code: "process_failed",
			message: "rojo sourcemap failed (exit code 1).\n  [ERROR] no such project",
		});
		expect(memory.files()).not.toContainKey("src/services.d.ts");
	});

	it("should fail with rojo_missing when Rojo is not installed", async () => {
		expect.assertions(1);

		const { context } = makeTypegen({ files: {} });

		await expect(runTypegenCommandAsync(context, input())).rejects.toMatchObject({
			code: "rojo_missing",
		});
	});

	it("should refuse a Luau project before running Rojo", async () => {
		expect.assertions(2);

		const { context, specs } = makeTypegen({ file: { projectType: "luau" } });

		await expect(runTypegenCommandAsync(context, input())).rejects.toMatchObject({
			code: "command_unavailable",
			hint: 'forge typegen applies only when projectType is "rbxts".',
			message:
				"forge typegen writes TypeScript declarations, which a Luau project does not use.",
		});
		expect(specs).toStrictEqual([]);
	});

	it("should run typegen hooks around Rojo and return their results", async () => {
		expect.assertions(2);

		const { context, order } = makeTypegen({
			file: { hooks: { typegen: { post: ["format"], pre: ["codegen"] } } },
		});
		const { data } = await runTypegenCommandAsync(context, input());

		expect(order()).toStrictEqual(["codegen", "rojo", "format"]);
		expect(data["hooks"]).toStrictEqual([
			expect.objectContaining({ id: "typegen:pre:0", outcome: "succeeded" }),
			expect.objectContaining({ id: "typegen:post:0", outcome: "succeeded" }),
		]);
	});

	it("should skip post hooks when Rojo fails", async () => {
		expect.assertions(2);

		const { context, order } = makeTypegen({
			file: { hooks: { typegen: { post: ["format"] } } },
			outcomes: { rojo: exited(1) },
		});

		await expect(runTypegenCommandAsync(context, input())).rejects.toMatchObject({
			code: "process_failed",
		});
		expect(order()).toStrictEqual(["rojo"]);
	});
});
