import type { InstanceGlob, InstancePath } from "./instance-glob.ts";
import { compileInstanceGlob } from "./instance-glob.ts";
import type { SourcemapNode } from "./sourcemap.ts";

/** Which instances get a type. Patterns are instance path globs. */
export interface TypegenFilter {
	/** An instance a pattern matches is left out, with everything under it. */
	exclude: ReadonlyArray<string>;
	/** An instance a pattern matches is typed, with its ancestors. */
	include: ReadonlyArray<string>;
	/** The deepest level to type; a service is level 1. */
	maxDepth: number | undefined;
}

/** What {@link generateServiceTypes} made. */
export interface GeneratedTypes {
	/**
	 * Instances left out because an earlier sibling has the same name, as
	 * `/`-joined paths.
	 */
	duplicates: Array<string>;
	/** The services that got an interface, in sourcemap order. */
	services: Array<string>;
	/** The declaration file's content. */
	source: string;
}

const HEADER = "// This file is autogenerated by rbx-forge. Do not modify.";

/**
 * Services never typed. Plugins under the debugger are not for game code, and
 * StarterPlayer's content is copied elsewhere at runtime.
 */
const BANNED_SERVICES: ReadonlySet<string> = new Set(["PluginDebugService", "StarterPlayer"]);

/** A name TypeScript accepts as a bare property key. */
const IDENTIFIER = /^[$A-Z_a-z][\w$]*$/;

/** One generation: the compiled filter and what it found. */
interface Generation {
	duplicates: Array<string>;
	exclude: ReadonlyArray<InstanceGlob>;
	include: ReadonlyArray<InstanceGlob>;
	maxDepth: number;
}

/**
 * Write the service types of a place: one interface per service, named after
 * its class, holding a property per child instance. TypeScript merges each
 * interface into the service's declaration from `@rbxts/types`.
 *
 * @param root - The place's root instance from the sourcemap.
 * @param filter - Which instances get a type.
 * @returns The declaration file's content and what it holds.
 */
export function generateServiceTypes(root: SourcemapNode, filter: TypegenFilter): GeneratedTypes {
	const generation: Generation = {
		duplicates: [],
		exclude: filter.exclude.map(compileInstanceGlob),
		include: filter.include.map(compileInstanceGlob),
		maxDepth: filter.maxDepth ?? Infinity,
	};
	const services: Array<string> = [];
	const interfaces: Array<string> = [];

	const candidates = typedChildren(generation, [], root.children);
	for (const service of candidates) {
		if (BANNED_SERVICES.has(service.name)) {
			continue;
		}

		const members = memberLines(generation, service.children, [service.name]);
		if (members.length > 0) {
			services.push(service.name);
			interfaces.push(`interface ${service.className} {\n${members.join("\n")}\n}`);
		}
	}

	const source =
		interfaces.length === 0 ? `${HEADER}\n` : `${HEADER}\n\n${interfaces.join("\n\n")}\n`;
	return { duplicates: generation.duplicates, services, source };
}

function matchesAny(globs: ReadonlyArray<InstanceGlob>, path: InstancePath): boolean {
	return globs.some((glob) => glob(path));
}

/**
 * The children the filter lets through, less any whose name an earlier one
 * has (those are recorded as duplicates).
 *
 * @param generation - The filter and the duplicates so far.
 * @param parent - The parent's path.
 * @param children - The children in sourcemap order.
 * @returns Each kept child.
 */
function typedChildren(
	generation: Generation,
	parent: InstancePath,
	children: ReadonlyArray<SourcemapNode> = [],
): Array<SourcemapNode> {
	const seen = new Set<string>();
	return children.filter(({ name }) => {
		const path = [...parent, name];
		if (path.length > generation.maxDepth || matchesAny(generation.exclude, path)) {
			return false;
		}

		if (seen.has(name)) {
			generation.duplicates.push(path.join("/"));
			return false;
		}

		seen.add(name);
		return true;
	});
}

/**
 * A property name: bare when it is an identifier, quoted otherwise.
 *
 * @param name - The instance's name.
 * @returns The name as a property key.
 */
function propertyName(name: string): string {
	return IDENTIFIER.test(name) ? name : JSON.stringify(name);
}

/**
 * The property lines for the typed children of one instance.
 *
 * @param generation - The filter and the duplicates so far.
 * @param children - The instance's children.
 * @param parent - The instance's path.
 * @returns One line (or block) per typed child.
 */
function memberLines(
	generation: Generation,
	children: ReadonlyArray<SourcemapNode> | undefined,
	parent: InstancePath,
): Array<string> {
	const lines: Array<string> = [];
	for (const child of typedChildren(generation, parent, children)) {
		const path = [...parent, child.name];
		const nested = memberLines(generation, child.children, path);
		if (nested.length === 0 && !matchesAny(generation.include, path)) {
			continue;
		}

		const indent = "\t".repeat(parent.length);
		const type =
			nested.length === 0
				? child.className
				: `${child.className} & {\n${nested.join("\n")}\n${indent}}`;
		// `@rbxts/types` declares Workspace.Terrain readonly, and merged
		// declarations must agree on modifiers.
		const isTerrain = path.join("/") === "Workspace/Terrain";
		lines.push(`${indent}${isTerrain ? "readonly " : ""}${propertyName(child.name)}: ${type};`);
	}

	return lines;
}
