import { describe, expect, it } from "vitest";

import type { TypegenFilter } from "./generate.ts";
import { generateServiceTypes } from "./generate.ts";
import type { SourcemapNode } from "./sourcemap.ts";

const HEADER = "// This file is autogenerated by rbx-forge. Do not modify.";

const ALL: TypegenFilter = { exclude: [], include: ["**"], maxDepth: undefined };

function instance(name: string, kind: string, ...children: Array<SourcemapNode>): SourcemapNode {
	// eslint-disable-next-line unicorn/no-keyword-prefix -- Rojo's key.
	const node: SourcemapNode = { name, className: kind };
	return children.length === 0 ? node : { ...node, children };
}

function place(...services: Array<SourcemapNode>): SourcemapNode {
	return instance("game", "DataModel", ...services);
}

/** A place with scripts, assets, and a nested folder in several services. */
const GAME = place(
	instance(
		"ReplicatedStorage",
		"ReplicatedStorage",
		instance(
			"Assets",
			"Folder",
			instance("Sword", "Tool", instance("Handle", "Part")),
			instance("Shield", "Model"),
		),
		instance("TS", "Folder", instance("util", "ModuleScript")),
	),
	instance("ServerScriptService", "ServerScriptService", instance("main", "Script")),
	instance("Workspace", "Workspace", instance("Terrain", "Terrain"), instance("Map", "Model")),
);

describe(generateServiceTypes, () => {
	it("should type every instance under each service", () => {
		expect.assertions(1);

		expect(generateServiceTypes(GAME, ALL)).toStrictEqual({
			duplicates: [],
			services: ["ReplicatedStorage", "ServerScriptService", "Workspace"],
			source: `${HEADER}

interface ReplicatedStorage {
	Assets: Folder & {
		Sword: Tool & {
			Handle: Part;
		};
		Shield: Model;
	};
	TS: Folder & {
		util: ModuleScript;
	};
}

interface ServerScriptService {
	main: Script;
}

interface Workspace {
	readonly Terrain: Terrain;
	Map: Model;
}
`,
		});
	});

	it("should write only the header when no instance is typed", () => {
		expect.assertions(1);

		expect(generateServiceTypes(place(), ALL)).toStrictEqual({
			duplicates: [],
			services: [],
			source: `${HEADER}\n`,
		});
	});

	it("should leave out services with no typed children", () => {
		expect.assertions(1);

		const game = place(
			instance("Lighting", "Lighting"),
			instance("Workspace", "Workspace", instance("Map", "Model")),
		);

		expect(generateServiceTypes(game, ALL).services).toStrictEqual(["Workspace"]);
	});

	it("should leave out StarterPlayer and PluginDebugService", () => {
		expect.assertions(1);

		const game = place(
			instance("PluginDebugService", "PluginDebugService", instance("Plugin", "Folder")),
			instance(
				"StarterPlayer",
				"StarterPlayer",
				instance("StarterPlayerScripts", "StarterPlayerScripts"),
			),
			instance("Workspace", "Workspace", instance("Map", "Model")),
		);

		expect(generateServiceTypes(game, ALL)).toStrictEqual({
			duplicates: [],
			services: ["Workspace"],
			source: `${HEADER}\n\ninterface Workspace {\n\tMap: Model;\n}\n`,
		});
	});

	it("should name the interface after the service's class", () => {
		expect.assertions(1);

		const game = place(instance("MyWorkspace", "Workspace", instance("Map", "Model")));

		expect(generateServiceTypes(game, ALL).source).toBe(
			`${HEADER}\n\ninterface Workspace {\n\tMap: Model;\n}\n`,
		);
	});

	it("should mark only Workspace.Terrain readonly", () => {
		expect.assertions(1);

		const game = place(
			instance(
				"Workspace",
				"Workspace",
				instance("Terrain", "Terrain", instance("Clouds", "Clouds")),
				instance("Map", "Model", instance("Terrain", "Folder")),
			),
			instance("Lighting", "Lighting", instance("Terrain", "Folder")),
		);

		expect(generateServiceTypes(game, ALL).source).toBe(`${HEADER}

interface Workspace {
	readonly Terrain: Terrain & {
		Clouds: Clouds;
	};
	Map: Model & {
		Terrain: Folder;
	};
}

interface Lighting {
	Terrain: Folder;
}
`);
	});

	it.for([
		["Part", "Part"],
		["_part", "_part"],
		["$part", "$part"],
		["Part2", "Part2"],
		["p_a$2", "p_a$2"],
		["2Part", '"2Part"'],
		["Red Part", '"Red Part"'],
		["red-part", '"red-part"'],
		["Part.1", '"Part.1"'],
		['Say "hi"', String.raw`"Say \"hi\""`],
		[String.raw`back\slash`, String.raw`"back\\slash"`],
		["line\nbreak", String.raw`"line\nbreak"`],
		["é", '"é"'],
		["", '""'],
	] as const)("should write the property for %j as %s", ([name, property]) => {
		expect.assertions(1);

		const game = place(instance("Workspace", "Workspace", instance(name, "Part")));

		expect(generateServiceTypes(game, ALL).source).toBe(
			`${HEADER}\n\ninterface Workspace {\n\t${property}: Part;\n}\n`,
		);
	});

	it("should keep the first of two siblings with one name and report the rest", () => {
		expect.assertions(1);

		const game = place(
			instance(
				"Workspace",
				"Workspace",
				instance("Part", "Part"),
				instance("Part", "MeshPart"),
				instance("Folder", "Folder", instance("Part", "Part"), instance("Part", "Part")),
			),
			instance("Workspace", "Workspace", instance("Other", "Part")),
		);

		expect(generateServiceTypes(game, ALL)).toStrictEqual({
			duplicates: ["Workspace", "Workspace/Part", "Workspace/Folder/Part"],
			services: ["Workspace"],
			source: `${HEADER}

interface Workspace {
	Part: Part;
	Folder: Folder & {
		Part: Part;
	};
}
`,
		});
	});

	describe("filters", () => {
		it("should type only instances an include pattern matches, with their ancestors", () => {
			expect.assertions(1);

			const filter = { ...ALL, include: ["ReplicatedStorage/Assets/Sword/**"] };

			expect(generateServiceTypes(GAME, filter)).toStrictEqual({
				duplicates: [],
				services: ["ReplicatedStorage"],
				source: `${HEADER}

interface ReplicatedStorage {
	Assets: Folder & {
		Sword: Tool & {
			Handle: Part;
		};
	};
}
`,
			});
		});

		it("should type a matched instance without its children when they do not match", () => {
			expect.assertions(1);

			const filter = { ...ALL, include: ["ReplicatedStorage/Assets", "Workspace/*"] };

			expect(generateServiceTypes(GAME, filter).source).toBe(`${HEADER}

interface ReplicatedStorage {
	Assets: Folder;
}

interface Workspace {
	readonly Terrain: Terrain;
	Map: Model;
}
`);
		});

		it("should type instances any include pattern matches", () => {
			expect.assertions(1);

			const filter = { ...ALL, include: ["**/Handle", "**/util"] };

			expect(generateServiceTypes(GAME, filter).source).toBe(`${HEADER}

interface ReplicatedStorage {
	Assets: Folder & {
		Sword: Tool & {
			Handle: Part;
		};
	};
	TS: Folder & {
		util: ModuleScript;
	};
}
`);
		});

		it("should type nothing with no include patterns", () => {
			expect.assertions(1);

			expect(generateServiceTypes(GAME, { ...ALL, include: [] }).source).toBe(`${HEADER}\n`);
		});

		it("should leave out an excluded instance and everything under it", () => {
			expect.assertions(1);

			const filter = { ...ALL, exclude: ["ReplicatedStorage/Assets/Sword", "Workspace/Map"] };

			expect(generateServiceTypes(GAME, filter).source).toBe(`${HEADER}

interface ReplicatedStorage {
	Assets: Folder & {
		Shield: Model;
	};
	TS: Folder & {
		util: ModuleScript;
	};
}

interface ServerScriptService {
	main: Script;
}

interface Workspace {
	readonly Terrain: Terrain;
}
`);
		});

		it("should let an exclude pattern win over an include pattern", () => {
			expect.assertions(1);

			const filter = {
				...ALL,
				exclude: ["ReplicatedStorage/Assets"],
				include: ["ReplicatedStorage/Assets/**", "ReplicatedStorage/TS/**"],
			};

			expect(generateServiceTypes(GAME, filter).source).toBe(`${HEADER}

interface ReplicatedStorage {
	TS: Folder & {
		util: ModuleScript;
	};
}
`);
		});

		it("should leave out a whole service an exclude pattern matches", () => {
			expect.assertions(1);

			const filter = { ...ALL, exclude: ["ReplicatedStorage", "ServerScriptService/**"] };

			expect(generateServiceTypes(GAME, filter).services).toStrictEqual(["Workspace"]);
		});

		it("should not report siblings that a filter left out", () => {
			expect.assertions(1);

			const game = place(
				instance(
					"Workspace",
					"Workspace",
					instance("node_modules", "Folder"),
					instance("node_modules", "Folder"),
					instance("Deep", "Folder", instance("Part", "Part"), instance("Part", "Part")),
				),
			);
			const filter = { exclude: ["**/node_modules/**"], include: ["**"], maxDepth: 2 };

			expect(generateServiceTypes(game, filter)).toStrictEqual({
				duplicates: [],
				services: ["Workspace"],
				source: `${HEADER}\n\ninterface Workspace {\n\tDeep: Folder;\n}\n`,
			});
		});

		it.for([
			[1, `${HEADER}\n`],
			[
				2,
				`${HEADER}

interface ReplicatedStorage {
	Assets: Folder;
	TS: Folder;
}

interface ServerScriptService {
	main: Script;
}

interface Workspace {
	readonly Terrain: Terrain;
	Map: Model;
}
`,
			],
			[
				3,
				`${HEADER}

interface ReplicatedStorage {
	Assets: Folder & {
		Sword: Tool;
		Shield: Model;
	};
	TS: Folder & {
		util: ModuleScript;
	};
}

interface ServerScriptService {
	main: Script;
}

interface Workspace {
	readonly Terrain: Terrain;
	Map: Model;
}
`,
			],
		] as const)(
			"should type instances down to level %i (a service is level 1)",
			([maxDepth, source]) => {
				expect.assertions(1);

				expect(generateServiceTypes(GAME, { ...ALL, maxDepth }).source).toBe(source);
			},
		);

		it("should not type an included instance deeper than the limit", () => {
			expect.assertions(1);

			const filter = { ...ALL, include: ["**/Handle"], maxDepth: 3 };

			expect(generateServiceTypes(GAME, filter).source).toBe(`${HEADER}\n`);
		});
	});
});
