import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { describe, expect, it, onTestFinished } from "vitest";

import { EXIT_FAILURE, EXIT_SUCCESS, EXIT_USAGE } from "../../src/exit-codes.ts";
import { createFixtureBinDirectory } from "../helpers/fixture-bin.ts";
import { parseResult } from "../helpers/output.ts";
import { killWorkers, readWorkerLog } from "../helpers/worker-log.ts";
import type { BinRun } from "./run-bin.ts";
import { makeProject, runBinAsync } from "./run-bin.ts";

const PATH_NAME = /^path$/i;
const HEADER = "// This file is autogenerated by rbx-forge. Do not modify.";

/** A place as `rojo sourcemap --include-non-scripts` writes it. */
const PLACE = [
	'{"name":"fixture","className":"DataModel","filePaths":["default.project.json"],"children":[',
	'{"name":"ReplicatedStorage","className":"ReplicatedStorage","children":[',
	'{"name":"Assets","className":"Folder","children":[',
	'{"name":"Sword","className":"Tool","filePaths":["assets/sword.rbxm"]}]},',
	'{"name":"TS","className":"Folder","children":[',
	'{"name":"util","className":"ModuleScript","filePaths":["out/util.luau"]}]}]},',
	'{"name":"StarterPlayer","className":"StarterPlayer","children":[',
	'{"name":"StarterPlayerScripts","className":"StarterPlayerScripts"}]},',
	'{"name":"Workspace","className":"Workspace","children":[',
	'{"name":"Terrain","className":"Terrain"},{"name":"Spawn Point","className":"SpawnLocation"}]}]}',
].join("");

interface Fixture {
	/** Run `forge` in the project with fake Rojo first on PATH. */
	forge: (argv: Array<string>, sourcemap?: string) => Promise<BinRun>;
	log: string;
	project: string;
}

/**
 * A project with an rbxts config and the fixture binaries alone on PATH.
 *
 * @param config - Config keys over `projectType: "rbxts"`.
 * @returns The project and a runner.
 */
function makeFixture(config?: object): Fixture {
	const project = makeProject();
	writeFileSync(
		path.join(project, "rbx-forge.config.json"),
		JSON.stringify({ projectType: "rbxts", ...config }),
	);
	const bin = createFixtureBinDirectory(path.join(project, "fixture-bin"));
	const log = path.join(project, "workers.ndjson");
	onTestFinished(() => {
		killWorkers(readWorkerLog(log));
	});

	const environment: NodeJS.ProcessEnv = { ...process.env, CI: undefined };
	// Windows spells it `Path`; two spellings would both reach the child.
	for (const key of Object.keys(environment)) {
		if (PATH_NAME.test(key)) {
			delete environment[key];
		}
	}

	return {
		forge: async (argv, sourcemap = PLACE) => {
			return runBinAsync(argv, project, {
				...environment,
				FIXTURE_LOG: log,
				FIXTURE_SOURCEMAP: sourcemap,
				PATH: bin,
				RBX_FORGE_HOOK_STACK: undefined,
			});
		},
		log,
		project,
	};
}

describe("forge typegen", () => {
	it("should write the service types of Rojo's sourcemap", async () => {
		expect.assertions(4);

		const { forge, project } = makeFixture();
		const { status, stdout } = await forge(["typegen", "--json"]);
		const output = path.join(project, "src", "services.d.ts");

		expect(status).toBe(EXIT_SUCCESS);
		expect(parseResult(stdout).data).toMatchObject({
			duplicates: [],
			hooks: [],
			output,
			services: ["ReplicatedStorage", "Workspace"],
		});
		expect(readFileSync(output, "utf8")).toBe(`${HEADER}

interface ReplicatedStorage {
	Assets: Folder & {
		Sword: Tool;
	};
	TS: Folder & {
		util: ModuleScript;
	};
}

interface Workspace {
	readonly Terrain: Terrain;
	"Spawn Point": SpawnLocation;
}
`);
		expect(existsSync(path.join(project, ".forge", "sourcemap.json"))).toBeFalse();
	});

	it("should pass the project and every instance to Rojo", async () => {
		expect.assertions(1);

		const { forge, log } = makeFixture({
			projectType: "rbxts",
			rojoProjectPath: "place.project.json",
		});
		await forge(["typegen"]);

		expect(readWorkerLog(log).map(({ args }) => args)).toStrictEqual([
			[
				"sourcemap",
				"place.project.json",
				"--output",
				path.join(".forge", "sourcemap.json"),
				"--include-non-scripts",
			],
		]);
	});

	it("should filter by --include, --exclude, and --max-depth, and write to --output", async () => {
		expect.assertions(2);

		const { forge, project } = makeFixture();
		const { status } = await forge([
			"typegen",
			"--include",
			"ReplicatedStorage/**",
			"--include",
			"Workspace/Terrain",
			"--exclude",
			"**/TS",
			"--max-depth",
			"2",
			"--output",
			"types/game.d.ts",
		]);

		expect(status).toBe(EXIT_SUCCESS);
		expect(readFileSync(path.join(project, "types", "game.d.ts"), "utf8")).toBe(`${HEADER}

interface ReplicatedStorage {
	Assets: Folder;
}

interface Workspace {
	readonly Terrain: Terrain;
}
`);
	});

	it("should exit 2 for a --max-depth below 1", async () => {
		expect.assertions(2);

		const { forge } = makeFixture();
		const { status, stdout } = await forge(["typegen", "--json", "--max-depth", "0"]);

		expect(status).toBe(EXIT_USAGE);
		expect(parseResult(stdout).error!.message).toStartWith("--max-depth: ");
	});

	it("should run typegen hooks around Rojo", async () => {
		expect.assertions(2);

		const { forge, log } = makeFixture({
			hooks: { typegen: { post: ["hook post"], pre: ["hook pre"] } },
			projectType: "rbxts",
		});
		const { status } = await forge(["typegen"]);

		expect(status).toBe(EXIT_SUCCESS);
		expect(readWorkerLog(log).map(({ args, role }) => `${role} ${args[0]!}`)).toStrictEqual([
			"hook pre",
			"rojo sourcemap",
			"hook post",
		]);
	});

	it("should fail with sourcemap_invalid and write nothing for a bad sourcemap", async () => {
		expect.assertions(3);

		const { forge, project } = makeFixture();
		const { status, stdout } = await forge(["typegen", "--json"], '{"name":"Tool"}');

		expect(status).toBe(EXIT_FAILURE);
		expect(parseResult(stdout).error!.code).toBe("sourcemap_invalid");
		expect(existsSync(path.join(project, "src"))).toBeFalse();
	});

	it("should refuse a Luau project", async () => {
		expect.assertions(3);

		const { forge, log } = makeFixture({ projectType: "luau" });
		const { status, stdout } = await forge(["typegen", "--json"]);

		expect(status).toBe(EXIT_FAILURE);
		expect(parseResult(stdout).error!.code).toBe("command_unavailable");
		expect(readWorkerLog(log)).toStrictEqual([]);
	});
});
